web:
  build: .
  volumes:
    - .:/opt/viveka-modules/viveka
  working_dir: /opt/viveka-modules/viveka
  ports:
    - 5555:5555
  environment:
    - DB_URI=mongodb://localhost:27017/viveka
    - FIREFOX_URI=http://localhost:4445/wd/hub
    - CHROME_URI=http://localhost:4446/wd/hub
  command: nodemon index.js | bunyan -o short
db:
  image: mongo:3.0
  net: container:web
firefox:
  image: selenium/standalone-firefox:2.46.0
  net: container:web
  environment:
    - DISPLAY=:98.0
    - JAVA_TOOL_OPTIONS="-Dselenium.port=4444"
chrome:
  image: selenium/standalone-chrome:2.46.0
  net: container:web
  environment:
    - DISPLAY=:99.0
    - JAVA_TOOL_OPTIONS="-Dselenium.port=4446"
galen:
  build: galen
  volumes:
    - galen:/opt/galen
  working_dir: /opt/galen
  command: sleep 5 && galen check homepage.spec --url "http://localhost:5555/testpage/#/element-added/baseline-view/no-header" --size "640x480" --include "mobile,all" --htmlreport "htmlreport-dir"
