dnsdock:
  image: tonistiigi/dnsdock:v1.6.0
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - "172.17.42.1:53:53/udp"
web:
  build: .
  volumes:
    - .:/opt/viveka-modules/viveka
  working_dir: /opt/viveka-modules/viveka
  ports:
    - 5555:5555
  dns: 172.17.42.1
  environment:
    - DB_URI=mongodb://viveka_db_1.mongo.docker:27017/viveka
    - FIREFOX_URI=http://viveka_firefox_1.standalone-firefox.docker:4444/wd/hub
    - CHROME_URI=http://viveka_chrome_1.standalone-chrome.docker:4444/wd/hub
  command: nodemon index.js | bunyan -o short
db:
  image: mongo:3.0
firefox:
  image: selenium/standalone-firefox:2.45.0
  dns: 172.17.42.1
chrome:
  image: selenium/standalone-chrome:2.45.0
  dns: 172.17.42.1
