web:
  build: .
  volumes:
    - .:/opt/app-modules/app
  working_dir: /opt/app-modules/app
  links:
    - db
  ports:
    - 5555:5555
  environment:
    - MONGO_DATABASE_URL=mongodb://db/viveka
  command: nodemon index.js
db:
  image: mongo:3.0
